[package]
name = "starknet_in_rust"
version = "0.4.0"
edition = "2021"
description = "A Rust implementation of Starknet execution logic"
license = "Apache-2.0"

[features]
default = ["with_mimalloc"]
with_mimalloc = ["dep:mimalloc"]
cairo_1_tests = []
metrics = []

[workspace]
members = ["cli", "fuzzer", "rpc_state_reader"]

[workspace.dependencies]
cairo-lang-casm = "2.2.0"
cairo-lang-runner = "2.2.0"
cairo-lang-sierra = "2.2.0"
cairo-lang-starknet = "2.2.0"
cairo-lang-utils = "2.2.0"
cairo-vm = { version = "0.8.5", features = ["cairo-1-hints"] }
num-traits = "0.2.15"
starknet = "0.5.0"
starknet_api = "0.4.1"
thiserror = "1.0.32"

[dependencies]
anyhow = "1.0.66"
base64 = { version = "0.21.0", default-features = false, features = ["alloc"] }
cairo-lang-casm = { workspace = true }
cairo-lang-runner = { workspace = true }
cairo-lang-sierra = { workspace = true }
cairo-lang-starknet = { workspace = true }
cairo-lang-utils = { workspace = true }
cairo-native = { git = "https://github.com/lambdaclass/cairo_native", rev = "312d8fbf7b1e6c417e3987dfea6d9e454c6d0412", optional = true }
cairo-vm = { workspace = true, features = ["cairo-1-hints"] }
flate2 = "1.0.25"
getset = "0.1.2"
hex = "0.4.3"
# TODO: Replace with sha3. We should look how to integrate it correctly to calculate sn_keccak
keccak = "0.1.3"
lazy_static = "1.4.0"
mimalloc = { version = "0.1.29", default-features = false, optional = true }
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1.45"
num-traits = { workspace = true }
once_cell = "1.17.1"
sha3 = "0.10.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_json_pythonic = "0.1.2"
starknet = { workspace = true }
starknet_api = { workspace = true }
starknet-crypto = "0.5.1"
thiserror = { workspace = true }
tracing = "0.1.37"

[dev-dependencies]
assert_matches = "1.5.0"
coverage-helper = "0.2.0"
pretty_assertions_sorted = "1.2.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[[bench]]
path = "bench/internals.rs"
name = "internals"
harness = false
