[package]
name = "starknet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-vm", features = ["cairo-1-hints"] }
getset = "0.1.2"
lazy_static = "1.4.0"
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1.45"
num-traits = "0.2.15"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sha3 = "0.10.1"
starknet_api = { git = "https://github.com/lambdaclass/starknet-api", rev="00e765267bc343269d28e38abfbf93014be6ce15", features = [
    "testing",
] }
starknet-crypto = "0.2.0"
thiserror = { version = "1.0.32" }
clap = { version = "4.1.8", features = ["derive"] }
actix-web = "4.3.1"
awc = "3.1.1"
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "44fdeb26231f5022f2441bf89018272460c4e326"}
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo", rev = "44fdeb26231f5022f2441bf89018272460c4e326"}
hex = "0.4.3"
cargo-llvm-cov = "0.5.14"

[dev-dependencies]
assert_matches = "1.5.0"
rusty-hook = "0.11"


[[bench]]
path = "bench/internals.rs"
name = "internals"
harness = false
