[package]
name = "starknet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-vm", rev = "77fe09ebbf72710935b455b1c5ff56b0bad7a4b8" }
felt = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-felt", rev = "77fe09ebbf72710935b455b1c5ff56b0bad7a4b8" }
getset = "0.1.2"
lazy_static = "1.4.0"
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1.45"
num-traits = "0.2.15"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sha3 = "0.10.1"
starknet_api = { git = "https://github.com/lambdaclass/starknet-api", branch = "main", features = [
    "testing",
] }
starknet-crypto = "0.2.0"
thiserror = { version = "1.0.32" }
clap = { version = "4.1.8", features = ["derive"] }
actix-web = "4.3.1"
awc = "3.1.1"

[dev-dependencies]
assert_matches = "1.5.0"
rusty-hook = "0.11"

[workspace]
members = ["crates/starknet-rs-py"]

[[bench]]
path = "bench/internals.rs"
name = "internals"
harness = false
