[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.55"
starknet-rs = { path = "../" }
felt = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-felt", rev = "77fe09ebbf72710935b455b1c5ff56b0bad7a4b8" }
num-traits = "0.2.15"
starknet_api = { git = "https://github.com/lambdaclass/starknet-api", branch = "main", features = [
    "testing",
] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tempfile = "3.2.0"
cairo-rs = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-vm", rev = "77fe09ebbf72710935b455b1c5ff56b0bad7a4b8" }
