[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.55"
starknet-rs =  { path = "../" }
num-traits = "0.2.15"
starknet_api = { git = "https://github.com/lambdaclass/starknet-api", branch = "main", features = ["testing"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tempfile = "3.2.0"
cairo-vm = { git = "https://github.com/lambdaclass/cairo-rs", rev = "327ee7d6778bdab9573573e6af008fcc6041f9ad" }

[profile.release]
strip = "debuginfo"
overflow-checks = true
opt-level = 3
debug = true
debug-assertions = true
