[package]
name = "starknet-contract-class"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"
getset = "0.1.2"
cairo-vm = { workspace=true, features = ["cairo-1-hints"]}
lambda_starknet_api = { workspace = true }
