[package]
name = "starknet-contract-class"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"

[dependencies.cairo-felt]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "11b6c379b96e452e671ec9bdeeebf1d85e584484"

[dependencies.cairo-vm]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "11b6c379b96e452e671ec9bdeeebf1d85e584484"

[dependencies.starknet_api]
git = "https://github.com/lambdaclass/starknet-api"
branch = "main"
features = ["testing"]
