[package]
name = "starknet-contract-class"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"

[dependencies.cairo-vm]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "327ee7d6778bdab9573573e6af008fcc6041f9ad"

[dependencies.starknet_api]
git = "https://github.com/lambdaclass/starknet-api"
branch = "main"
features = ["testing"]
