[package]
name = "starknet-contract-class"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"

[dependencies.cairo-vm]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "593d9a739fe3f1734c4d19d1dd037a5e3a734a57"

[dependencies.starknet_api]
git = "https://github.com/lambdaclass/starknet-api"
branch = "main"
features = ["testing"]
