[package]
name = "starknet-contract-class"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"

[dependencies.cairo-felt]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "eebfd612c5f969c759cb982e8fb777b2a1a1dab0"

[dependencies.cairo-vm]
git = "https://github.com/lambdaclass/cairo-rs.git"
rev = "eebfd612c5f969c759cb982e8fb777b2a1a1dab0"

[dependencies.starknet_api]
git = "https://github.com/lambdaclass/starknet-api"
branch = "main"
features = ["testing"]
