name: rust-tests

on:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.70.0

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Deps
      run: make deps
    - name: Build
      run: make build

  format:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Deps
      run: make deps
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: make clippy

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Deps
      run: make deps
    - name: Run tests
      run: make test
    - name: Run doctests
      run: cargo test --workspace --doc

  # 28.06.2023: This job uses unmaintained actions-rs because dtolnay is giving linking errors with nightly
  coverage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Deps
      run: make deps
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Coverage
      run: make coverage
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
